#!/usr/bin/env python3
"""
Refactor PR Generator — called by Hermes /generate-refactor-pr skill
Install: pip install PyGithub anthropic python-dotenv
Place at: ~/.hermes/scripts/generate_refactor_pr.py
"""

import json
import os
from datetime import datetime
from pathlib import Path

import anthropic
from dotenv import load_dotenv
from github import Github

load_dotenv(Path.home() / ".hermes" / ".env")

GITHUB_TOKEN  = os.environ["GITHUB_TOKEN"]
GITHUB_REPO   = os.environ["GITHUB_REPO"]
ANTHROPIC_KEY = os.environ["ANTHROPIC_API_KEY"]
BASE_BRANCH   = os.environ.get("REFACTOR_BASE_BRANCH", "main")
REPORT_PATH   = Path(os.environ.get("DEBT_REPORT_PATH", "/tmp/debt_report.json"))

REFACTOR_PROMPT = """You are an expert Python engineer. Refactor the following function to fix this issue:

Issue: {detail}
File: {file_path}
Function: {function_name}

Here is the relevant code (the target function is between the markers):

```python
{code_context}
```

Rules:
- Return ONLY the refactored function(s) as valid Python code, no markdown fences
- Preserve the original function signature and return type
- Keep all existing functionality — this is a structural refactor only
- Add a brief docstring if one is missing
- If splitting a long function, return all new helper functions too
"""

def get_code_context(content: str, line_start: int, line_end: int, context: int = 20) -> str:
    lines = content.splitlines()
    start = max(0, line_start - context - 1)
    end   = min(len(lines), line_end + context)
    snippet = lines[start:end]
    # Mark the target function
    rel_start = line_start - start - 1
    rel_end   = line_end   - start
    snippet.insert(rel_end,   "# ── END TARGET ──")
    snippet.insert(rel_start, "# ── BEGIN TARGET ──")
    return "\n".join(snippet)

def call_claude(prompt: str) -> str:
    client = anthropic.Anthropic(api_key=ANTHROPIC_KEY)
    msg = client.messages.create(
        model="claude-opus-4-20250514",
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )
    return msg.content[0].text.strip()

def replace_function(original: str, refactored: str, line_start: int, line_end: int) -> str:
    lines = original.splitlines()
    return "\n".join(lines[:line_start - 1] + refactored.splitlines() + lines[line_end:])

def create_pr(repo, debt: dict, new_content: str, file_path: str) -> str:
    ts = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    branch = f"refactor/auto-{debt['debt_type'].replace('_','-')}-{ts}"

    base_sha = repo.get_branch(BASE_BRANCH).commit.sha
    repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)

    existing = repo.get_contents(file_path, ref=BASE_BRANCH)
    repo.update_file(
        path=file_path,
        message=f"refactor: auto-fix {debt['debt_type']} in {debt['function_name']}",
        content=new_content,
        sha=existing.sha,
        branch=branch,
    )

    pr = repo.create_pull(
        title=f"[Auto Refactor] {debt['function_name']} in {file_path}",
        body=(
            f"## Auto-generated refactor\n\n"
            f"**Issue**: {debt['detail']}\n\n"
            f"**Debt type**: `{debt['debt_type']}`\n"
            f"**Severity**: `{debt['severity']}`\n"
            f"**Metric**: {debt['current_value']} (threshold: {debt['threshold']})\n\n"
            f"---\n_Generated by Hermes refactor-agent. Please review before merging._"
        ),
        head=branch,
        base=BASE_BRANCH,
        draft=True,
    )
    try:
        pr.add_to_labels("auto-refactor", "tech-debt")
    except Exception:
        pass
    return pr.html_url

# ── main ──────────────────────────────────────────────────────────────────────
if not REPORT_PATH.exists():
    print(f"[pr-gen] ERROR: {REPORT_PATH} not found. Run /scan-tech-debt first.")
    raise SystemExit(1)

report = json.loads(REPORT_PATH.read_text())
debts  = report["debts"]
print(f"[pr-gen] Processing {len(debts)} debts from report ...")

g    = Github(GITHUB_TOKEN)
repo = g.get_repo(GITHUB_REPO)

results = []
for i, debt in enumerate(debts, 1):
    print(f"[pr-gen] ({i}/{len(debts)}) {debt['function_name']} in {debt['file_path']} ...")
    try:
        file_content = repo.get_contents(debt["file_path"], ref=BASE_BRANCH).decoded_content.decode("utf-8")
        context = get_code_context(file_content, debt["line_start"], debt["line_end"])
        prompt  = REFACTOR_PROMPT.format(context=context, **{k: debt[k] for k in ("detail","file_path","function_name")})
        refactored_code = call_claude(prompt)
        new_content = replace_function(file_content, refactored_code, debt["line_start"], debt["line_end"])
        pr_url = create_pr(repo, debt, new_content, debt["file_path"])
        print(f"[pr-gen]   ✅ PR created: {pr_url}")
        results.append({"debt": debt["function_name"], "pr_url": pr_url, "status": "ok"})
    except Exception as e:
        print(f"[pr-gen]   ❌ Failed: {e}")
        results.append({"debt": debt["function_name"], "error": str(e), "status": "failed"})

print("\n[pr-gen] Summary:")
for r in results:
    status = "✅" if r["status"] == "ok" else "❌"
    detail = r.get("pr_url") or r.get("error")
    print(f"  {status} {r['debt']}: {detail}")
